### ISSUE TITLE
Support of template ?

### ISSUE THREAD

**Issue by RobinHerzog** [birkir/gatsby-source-prismic-graphql#1]
Hello,

I dont use pages but only templates.

Do you think it is possible to use it?

**Comment by birkir** [comment]
Yes, but the catch is, you have to wrap your template with the following decorator

```jsx
import { withPreview } from 'gatsby-source-prismic-graphql';

class YourTemplate extends React.Component {}

export default withPreview(YourTemplate);
```

**Comment by RobinHerzog** [comment]
I set withPreview function. For now I see no changes in preview. 

Does it support slice ?

What should the url looks like in preview mode ?

**Comment by birkir** [comment]
I refactored the plugin drastically.

I have included template support with a new feature called `componentResolver`, which is similar to linkResolver, but renders a component if the page was not found.
