### ISSUE TITLE
Should single types be in an array?

### ISSUE THREAD

**Issue by xndyz** [birkir/gatsby-source-prismic-graphql#107]
I have a single type called "Homepage", but the local GraphQL API treats it as a repeatable type. Calls it `allHomePages`, which is misleading since there can only be one of that type. Yet it returns a single item array. Accessing it is not very clean as well.

Could the API change to reflect the singularity of single types? Otherwise seems kind of weird to have that distinction in the CMS.

**Comment by Duaner** [comment]
Hey, @fandy this is something that will have to be improved in the prismic graphQL API and that is not really an issue of the plugin. 

I note that as a feature request for prismic but I think this issue can be closed.  @birkir
