### ISSUE TITLE
load() pagination returns old data on last page

### ISSUE THREAD

**Issue by ffdead** [birkir/gatsby-source-prismic-graphql#11]
Hey,

I was just testing out pagination/filtering using the provided `load()` function and noticed what I think is a bug:

When reaching the last page, the result will contain old data merged with the last page if the last page result is less than the pageSize. I'm seeing data from `lastPage-1` merged with the single item from the last page.

I think it's because of this line? https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/src/withPreview.tsx#L108

Is there any way we could get it to only return the new items on the last page?

This also becomes a problem when trying to filter the results.

**Comment by birkir** [comment]
That's a good question. If I don't do the merge, we will loose all other data that's unrelated to this plugin.

I could try to merge everything but the result and then replace the result. Does that make sense?

**Comment by ffdead** [comment]
I think that makes sense. Could we try that?

I also wonder if this would impact paginating multiple cursors, I guess that should work?

**Comment by birkir** [comment]
Can you try the 3.0.0 version of the plugin

**Comment by ffdead** [comment]
Unable to test on `3.0.0-alpha.14`.

Seems like the `load()` function is no longer adding my `after` variable to the query so next page is never fetched.

Code used to trigger request: 

`prismic.load({ after: pageInfo.endCursor, first: pageSize })`

Resulting query request:
´´´
https://antlerco.prismic.io/graphql?query=query%20NewsPageQuery(%24filter%3A%20Boolean!%20%3D%20false%2C%20%24industryFilter%3A%20String%2C%20%24first%3A%20Int%20%3D%2020%2C%20%24after%3A%20String)%20%7B%0A%20%20allFilters%3A%20allIndustry_tags%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20allAdvisors(first%3A%20%24first%2C%20after%3A%20%24after)%20%40skip(if%3A%20%24filter)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20filteredAdvisors%3A%20allAdvisors(first%3A%20%24first%2C%20after%3A%20%24after%2C%20where%3A%20%7Bindustry%3A%20%24industryFilter%7D)%20%40include(if%3A%20%24filter)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A&operationName=NewsPageQuery&variables=%7B%22filter%22%3Afalse%2C%22first%22%3A20%7D
´´´

**Comment by birkir** [comment]
The load now takes a `variables` property.

So try: `prismic.load({ variables: { after: pageInfo.endCursor, first: pageSize } })`

**Comment by ffdead** [comment]
Great, using `variables` will pass it properly to the GraphQL query. I can see the proper request being made, and the new page data coming back in the Prismic response. 

However, the page data prop never updates with the response. So the new data doesn't render.

**Comment by birkir** [comment]
Thats to give you more control, so you can do something very very simple like this:

```jsx
export default function Home(props) {

  const [data, setData] = React.useState(props.data.prismic);

  const handleClick = () => props.prismic.load({ ... })
    .then(setData);

  return ( ... );
}
```
