### ISSUE TITLE
Error: Schema must contain uniquely named types but contains multiple types named "DateTime".

### ISSUE THREAD

**Issue by brinsknaps** [birkir/gatsby-source-prismic-graphql#121]
Thanks ahead of time for any responses. I'm very new to Gatsby and Prismic. I'm just trying to follow along the [Gatsby + Prismic](https://prismic.io/docs/reactjs/getting-started/prismic-gatsby) tutorial. After updating gatsby-config.js and gatsby-browser.js, I run 'gatsby develop' then get the following result and am not sure how to resolve this:

success open and validate gatsby-configs - 0.107s
success load plugins - 0.134s
success onPreInit - 0.003s
success initialize cache - 0.019s
success copy gatsby files - 0.057s
success onPreBootstrap - 0.007s
success createSchemaCustomization - 0.002s

 ERROR #11321  PLUGIN

"gatsby-source-prismic-graphql" threw an error while running the sourceNodes lifecycle:

Schema must contain uniquely named types but contains multiple types named "DateTime".

  Error: Schema must contain uniquely named types but contains multiple types named "DateTime".
  
  - Array.reduce
  
  - transforms.js:11 
    [my_project]/[graphql-tools]/dist/transforms/transforms.js:11:54
  
  - Array.reduce
 
success source and transform nodes - 1.027s
success building schema - 0.284s
⠋ createPages

 ERROR 

UNHANDLED REJECTION ENOENT: no such file or directory, open [...]/dev/my_project/node_modules/gatsby-source-prismic-graphql/gatsby-node.js'

  Error: ENOENT: no such file or directory, open '[...]/dev/my_project/node_modules/gatsby-source-prismic-graphql/gatsby-node.js'
  
⠋ createPages

**Comment by GoldenRatio3** [comment]
I believe it's trying to determine the type, try putting in some dummy data through the prismic dashboard e.g. one for each custom type created

**Comment by brinsknaps** [comment]
@GoldenRatio3 Yup. That definitely got me through that error. I really appreciate the response!
