### ISSUE TITLE
Error when previewing unpublished pages on localhost that matches the pattern `article/:uid`

### ISSUE THREAD

**Issue by LJNGDAHL** [birkir/gatsby-source-prismic-graphql#126]
### Description

I want to preview an automatically generated page that matches the pattern `/article/:uid`. The page is unpublished and I am trying to access it on `localhost`. 

Previewing the same page on my staging site works fine, the page is accessible under `/article?uid=baz`. But when previewing it on localhost, I am routed to `/article/baz`. This results in an error since this page is not published.

### Steps to Reproduce

Add the following snippet in your `gatsby-config.js` (together with other settings): 

```javascript
pages: [
          {
            type: 'Page',
            match: '/:uid',
            path: '/page',
            component: require.resolve('./src/templates/page.js')
          },
          {
            type: 'Article',
            match: '/article/:uid',
            path: '/article',
            component: require.resolve('./src/templates/article.js')
          }
        ]

```

And in your `linkResolver.js`: 

```javascript
export const linkResolver = doc => {
  if (doc.type === 'article') {
    return `/article/${doc.uid}`
  }

  if (doc.type === 'page') {
    return `/${doc.uid}`
  }

  // Backup for all other types
  return '/'
}
```

**Expected behavior:**
Unpublished article pages should accessible for preview on localhost under `/article?uid=baz`.

**Actual behavior:** 

Unpublished article page is not accessible for preview on localhost.

### Versions
```
"gatsby": "2.18.11"
"prismic-reactjs": "1.1.2",
"gatsby-source-prismic-graphql": "3.4.0-beta.2"
```

**Comment by Mallika1** [comment]
I have the same problem previewing the unpublished documents.

**Comment by LJNGDAHL** [comment]
What I've found out is that the problem actually exists on my staging/production sites as well. If I want to preview unpublished documents, I have to:

1. Click on the preview link
1. Manually update the url to match the pattern `/article?uid=baz`
1. Reload the preview. 

If I do this, I preview the document as intended.

**Comment by Mallika1** [comment]
when I had top level page created i.e.  localhost://article , I was not able to preview the unpublished document . but when I removed article page , it worked for me . Though i need the top level page to be created.
