### ISSUE TITLE
broken only on production

### ISSUE THREAD

**Issue by deebov** [birkir/gatsby-source-prismic-graphql#147]
hey there
I've been stuck on this issue for a while now. Everything is perfect on development. But on production links and images aren't working correctly. it reloads the page when clicking on any link. I see this error in the console:
![image](https://user-images.githubusercontent.com/28673719/75259669-30ced500-580a-11ea-9cde-cb77705d9189.png)

I tried to upgrade to beta and canary. none of them has helped. I noticed that when I switched from `3.3.1` to beta and canary I started to see the error above instead of `Uncaught TypeError: Cannot set property 'query' of undefined`

Steps to reproduce:
1. `gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog`
2. `cd gatsby-starter-blog`
3. `yarn add gatsby-source-prismic-graphql`
4. add this code below to the plugins array in `gatsby-config.js`
```js
    {
      resolve: "gatsby-source-prismic-graphql",
      options: {
        repositoryName: "your-repo",
        accessToken:
          "your-access-token",
      },
    },
```
5. And voila! your app is automatically broken even though you haven't changed anything in the `src` folder

**Comment by deebov** [comment]
@birkir do you have any idea what might be causing the issue?

**Comment by aodysseos** [comment]
Have you seen this: https://github.com/birkir/gatsby-source-prismic-graphql/issues/77

**Comment by deebov** [comment]
> Have you seen this: #77

Thank you. It fixed the issue
