### ISSUE TITLE
414 (Request-URI Too Large)

### ISSUE THREAD

**Issue by ffdead** [birkir/gatsby-source-prismic-graphql#15]
Just ran into this problem with a longer page query. It seems the GraphQL GET request has a limitation on the query length in Prismic.

Could we send the query using POST instead? I noticed the Gatbsy graphql tool uses that to send the query and the same query works fine there. 

My query as a reference below.
```sh
curl 'https://antlerco.prismic.io/graphql?query=query%20TeamPageQuery(%24filter%3A%20Boolean!%20%3D%20false%2C%20%24industryFilter%3A%20String%2C%20%24first%3A%20Int%20%3D%201%2C%20%24afterAdvisor%3A%20String)%20%7B%0A%20%20team_page(uid%3A%20%22team-page%22%2C%20lang%3A%20%22en-us%22)%20%7B%0A%20%20%20%20hero_title%0A%20%20%20%20introduction%0A%20%20%20%20body%20%7B%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20...%20on%20Team_pageBodyAll_team_members%20%7B%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20...%20on%20Team_pageBodyAdvisor_list%20%7B%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20%20%20featured_advisor%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Advisor%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20company%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20headshot%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20industry%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Industry_tag%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20uid%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20...%20on%20Team_pageBodyAdvisor_testimonials%20%7B%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20%20%20advisor%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Advisor%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20company%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20headshot%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20industry%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Industry_tag%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20uid%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20advisor_image%0A%20%20%20%20%20%20%20%20%20%20testimonial_text%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20allLocations%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20uid%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20body%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20LocationBodyTeam_grid%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20team_member%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Team_member%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20headshot%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20allIndustry_tags%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20allAdvisors(first%3A%20%24first%2C%20after%3A%20%24afterAdvisor)%20%40skip(if%3A%20%24filter)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20industry%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20Industry_tag%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20filteredAdvisors%3A%20allAdvisors(first%3A%20%24first%2C%20after%3A%20%24afterAdvisor%2C%20where%3A%20%7Bindustry%3A%20%24industryFilter%7D)%20%40include(if%3A%20%24filter)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20_meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A&operationName=TeamPageQuery&variables=%7B%22filter%22%3Afalse%2C%22first%22%3A2%2C%22afterAdvisor%22%3A%22YXJyYXljb25uZWN0aW9uOjA%3D%22%7D' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: http://localhost:8000' -H 'Referer: http://localhost:8000/team' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' -H 'Access-Control-Request-Headers: content-type,prismic-ref' --compressed
```
Lots of whitespace in there but, even if that could be stripped out, it doesn't feel good to have to worry about query lengths.

I guess Fragments support #10 would help reduce the size, but that is also not fixing the real problem.

**Comment by birkir** [comment]
Can you try the 3.0.0 version of the plugin

**Comment by ffdead** [comment]
Getting the same error with `3.0.0-alpha.14`

Related? 
https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/packages/gatsby-source-prismic-graphql/src/utils/index.ts#L66

**Comment by ffdead** [comment]
I just found this in the Prismic docs, seems like the query have to be a `GET` request:

> Important to know: contrary to a classic GraphQL API, you need to use a GET request to query the Prismic GraphQl API.

https://prismic.io/docs/graphql/getting-started/intro-to-the-graphql-api#18_1-a-graphql-api-that-uses-get

Is there another solution to avoid doing long queries? Maybe a way to do multiple queries for a page in Gatsby?

**Comment by birkir** [comment]
Cool, no problem, thanks! Yes seems like Prismic will have have to open for POST queries.

Unfortunately they don't support it yet.

**Comment by ffdead** [comment]
Reply from Arnaud Lewis on the Prismic slack:

> The graphql feature is still at alpha stage and we didn't implement a workaround for it but we have an idea of an implementation. We'll still go with GET request to get some cache on the CDN side. 
In the meantime, I have no solution except downsizing the request for now.

**Comment by birkir** [comment]
Now with fragment support I was able to shrink your query a lot!

|    | bytes | decoded bytes |
| -- | -- | -- |
| Original | 8,279 | 3,825 |
| Fragments | 4,939 | 2,539 |
| Removed Whitespace | 2,362 | 1,680 |

I think most servers have a **limit of 2048 bytes** so we have to stick with that.

You could also potentially use StaticQuery for things that isn't using variables and get this down to a whopping 850 bytes!

Should I strip whitespace by default in the plugin? `query.replace(/\s+/g, ' ')`

**Comment by ffdead** [comment]
Great stuff!

Given that there is a size limit, I think it would be great if the plugin stripped white space automatically.

**Comment by birkir** [comment]
Fragments + Whitespace stripped, I will close this issue for now as it is unsolvable.

Feel free to re-open to ask for tips how to reduce the query size, but consider the following:

1. Use fragments
2. Use StaticQuery for data not needing variables
3. Do you really need all the properties?

**Comment by kkor** [comment]
I ran into this issue as well, not sure if this is fixable here, but would be nice if the error was reported correctly. Now with the current examples (are they using 3.0.2 even if the package.json lists 3.0.0-alpha.0 as dependency?) the error message is:

The GraphQL query from /src/templates/Page.tsx failed.

Errors:
  Unexpected token < in JSON at position 0

  GraphQL request (5:5)
  4:   prismic {
  5:     page(uid: $uid, lang: "en-us") {
         ^
  6:       title

Even the __graphQL response in graphiQL only says:
"{"errors":[{"message":"Unexpected token < in JSON at position 0","locations":[{"line":3,"column":5}],"path":["prismic","page"]}],"data":{"prismic":{"page":null}}}"
 
To get the correct error message (414 - Request-URI Too Large) you have to adjust the query and use Prismic's graphiQL instead (https://myrepo.prismic.io/graphql).

**Comment by birkir** [comment]
@kkor this has now been fixed with 3.0.5
Also stripping on the server

**Comment by kkor** [comment]
Til Hamingju for being officially featured by Prismic https://prismic.io/blog/prismic-gatsby-preview-plugin! 🙂
(Maybe consider adding the link to the README?)

I'd like to propose re-opening this issue - even though you cannot solve it on your end - and/or more importantly add a mention of this issue in the README, because it is seriously a major blocker for anyone who plans on using slices (or just abnormally large custom types) in prismic though the GraphQL API. 

If you are planning on using 5-10 slices (depending on how big they are) and especially if you're using links to other prismic documents, you're very likely to run into the Request-URI Too Large limit when querying document content in templates. And the bad news is that no amount of fragmenting and minimizing the request is going to get around it and Prismic refused to make any promises as to when they might fix this / tell how high of a priority this was for them. 

All the workarounds I've come up with a unideal:
* Splitting your slices into multiple custom types in prismic (e.g. grouping slices based on what documents they are used in, query something based on uid with static queries when possible, ...)
    * Not a real solution: because the more custom types the more bloat you introduce in both prismic document links and graphql queries and undoing this is a pain
* Query the largest slices by using prismic.load to dynamically load the content of the slice outside of the template queries
    * Haven't actually tried this, but as long as you can pass all variables down to the query with the extra slice content, I don't see why this wouldn't work (although now that I think about it, there's a problem with prismic.load in IE11, that's maybe related because it had a similar fix: making the query smaller prevented the primic.load from throwing errors) 
    * Impacts end user load times negatively
    * Using static queries to fetch the content of a slice is not possible, because you can't pass variables to those
* Query the some of the slice content in gatsby-node.js in createPages with as many graphQL queries as needed, maybe even split the graphql queries based on the document properties, then pass all data down to templates through the page context
    * Haven't tried this one yet either, but I'm leaning toward this solution, because moving all the queries into gatsby-node will probably give a performance boost to the build times too (currently at 2+ minutes :/): https://github.com/gatsbyjs/gatsby/issues/7373#issuecomment-434097369
* other ideas are welcome?

**Comment by bostrom** [comment]
I ran into this myself the other day and now I'm curious as to how I can inspect the graphql query that is fired off towards Prismic. @ffdead how did you get that URL for the curl command?

**Comment by ffdead** [comment]
> I ran into this myself the other day and now I'm curious as to how I can inspect the graphql query that is fired off towards Prismic. @ffdead how did you get that URL for the curl command? 

@bostrom I think I found it in the networks tab as a failed request (dev tools in Chrome)

**Comment by bostrom** [comment]
@ffdead Thanks. Ah, so the query was done live from the browser, not on build time... That makes it easier I guess. 

Unfortunately I need to debug it in the build process, so I ended up connecting with Node inspector and drilling down into the depths of this plugin and gatsby itself 😞

**Comment by ffdead** [comment]
> @ffdead Thanks. Ah, so the query was done live from the browser, not on build time... That makes it easier I guess. 
> 
> 
> 
> Unfortunately I need to debug it in the build process, so I ended up connecting with Node inspector and drilling down into the depths of this plugin and gatsby itself 😞 
> 
> 

@bostrom ah yes, my original problem happened during a preview session

**Comment by mad-gav** [comment]
Also running into this issue

![image](https://user-images.githubusercontent.com/60468535/88658060-c547a700-d0ca-11ea-9a0f-76392121d2b5.png)

Wondering if i can do more to fix this. Seems weird to be using a GET request
