### ISSUE TITLE
/preview request throws an error

### ISSUE THREAD

**Issue by ruslansavenok** [birkir/gatsby-source-prismic-graphql#153]
```
Unhandled Rejection (TypeError): Cannot read property 'options' of undefined

PreviewPage.js
}, {
    key: "config",
    get: function get() {
      return this.props.prismic.options;
    }
  }]);
```

gatsby-source-prismic-graphql@3.5.0

**Comment by ruslansavenok** [comment]
Example link http://localhost:8000/preview?token=https%3A%2F%2Ftest-ruslan.prismic.io%2Fpreviews%2FXl_OpRIAACEAPTM5%3AXmFFgBIAACEAQ5UA%3FwebsitePreviewId%3DXl0RMxIAACAAQf8T&documentId=Xl6ovBIAACMAOBfZ

**Comment by Giulico** [comment]
Hi @ruslansavenok, how did you solve this issue? I've the exactly the same error.
