### ISSUE TITLE
[question] - Is there a way of generating index.js from a template?

### ISSUE THREAD

**Issue by jodiedoubleday** [birkir/gatsby-source-prismic-graphql#172]
I have 1 custom type in Prismic I want to use for all page types.

If I set the UID in Prismic to be index, `localhost:9000/index` works fine but `localhost:9000/` (i actually get a flash of the page I want, then a white screen).

Does anyone know the best way to make this work?

**Comment by samponeill** [comment]
have you tried using a filter? Something like this in your config

`        {
          type: 'Landing_page',
          filter: data => data.node._meta.uid.includes('index'),
          path: '/',
          component: require.resolve('./src/components/05 Pages/index.js')
        },
        {
          type: 'Landing_page',
          filter: data => !data.node._meta.uid.includes('index'),
          path: '/:uid',
          component: require.resolve('./src/components/05 Pages/index.js')
        },   `

**Comment by jodiedoubleday** [comment]
I'll give this a try, though I'm sure when I tried this before it resulted in a flash of the right page before going blank
