### ISSUE TITLE
3.0.0-alpha.14 Preview not updating page content

### ISSUE THREAD

**Issue by ffdead** [birkir/gatsby-source-prismic-graphql#18]
I can't get the Preview to update the page content using `3.0.0-alpha.14`

This is a static page where the Prismic toolbar shows the preview content but not the page: 

https://www.dropbox.com/s/75ha7wo2h4803m8/Screenshot%202019-03-20%2011.00.45.png?dl=0

Same for dynamically created pages using the `pages:` property, it's not updating the content. 

You can see the Prismic toolbar has the updated title, but not the page content:
https://www.dropbox.com/s/3q8m3jrdo62yley/Screenshot%202019-03-20%2010.26.41.png?dl=0

**Comment by akilham** [comment]
@birkir was there a solution to this? I'm having the same problem (no errors in console) and I don't know why. Happy to post a new thread but thought I'd ask here as I'm not sure why this was closed!

![image](https://user-images.githubusercontent.com/5276669/57357816-31cd4200-71b7-11e9-9607-7f55e6a07f81.png)
