### ISSUE TITLE
3.0.0-alpha.14 __typename did not match an object type: PRISMIC__ExternalLink

### ISSUE THREAD

**Issue by ffdead** [birkir/gatsby-source-prismic-graphql#19]
The GraphQL type `PRISMIC__ExternalLink` seems to be missing in this version. All queries for documents with external links fails.

Internal Document links seem to resolve properly.

Reference error:
> __typename did not match an object type: PRISMIC__ExternalLink
https://www.dropbox.com/s/ge7nkq8jaj0onko/Screenshot%202019-03-20%2011.06.21.png?dl=0

**Comment by birkir** [comment]
Works fine for me. How is this setup for you?

![image](https://user-images.githubusercontent.com/180773/54693987-ecb55980-4afd-11e9-90a8-7b5b3523eb06.png)

**Comment by birkir** [comment]
Feel free to re-open

**Comment by ffdead** [comment]
Not sure what could be different, but this is what I get when compiling:

This is my page schema:

```json
{
  "Main" : {
    "title" : {
      "type" : "StructuredText",
      "config" : {
        "single" : "heading1",
        "label" : "Title"
      }
    },
    "test_link_field" : {
      "type" : "Link",
      "config" : {
        "label" : "Test Link Field"
      }
    }
}
```

This is my query: 

```jsx
query Home {
    prismic {
      global_home(uid: "home", lang: "en-us") {
        title
        page_meta_title
        page_meta_description
        test_link_field {
          _linkType
          __typename
        }
      }
    }
  }
```

And this is the error I get.

```sh
success update schema — 0.147 s
success extract queries from components — 0.115 s
error
The GraphQL query from /Users/davidlindkvist/Documents/git-repos/antler-website/src/pages/index.js failed.

Errors:
  __typename did not match an object type: PRISMIC__ExternalLink

  GraphQL request (7:7)
  6:       page_meta_description
  7:       test_link_field {
           ^
  8:         _linkType

```

However, if I launch the Gatsby dev server without this field in the query, and then later add it runtime while previewing, I get this back from  the preview graphql request:

```json
{
  "data":{
    "global_home":{
      "test_link_field":{
        "_linkType":"Link.web",
        "__typename":"_ExternalLink"
      }
      ,"__typename":"Global_home"
    }
  }
}
```

There the typename is `_ExternalLink` without the PRISMIC prefix - dunno if that helps you at all?

**Comment by birkir** [comment]
For others who have this happening, this only happens on latest Gatsby version, downgrade if you have problems.

Until this goes through: https://github.com/gatsbyjs/gatsby/pull/12721

**Comment by wcisco17** [comment]
Upgrade to version 

```
"gatsby": "^2.17.7",
```

Worked for me

**Comment by kilinkis** [comment]
This is happening to me on gatsby@2.20.13 and latest gatsby-source-prismic-graphql
