### ISSUE TITLE
Updating from 2.2.0 -> 3.0.2

### ISSUE THREAD

**Issue by kkor** [birkir/gatsby-source-prismic-graphql#22]
Hey again,

I tried updating to the latest version, but gatsby develop throws:

error Plugin gatsby-source-prismic-graphql returned an error

  SyntaxError: Unexpected token, expected "," (206:39)

  - index.js:3831 Object.raise
    [Website]/[@babel]/parser/lib/index.js:3831:17

  - index.js:5143 Object.unexpected
    [Website]/[@babel]/parser/lib/index.js:5143:16

  - index.js:5135 Object.expect
    [Website]/[@babel]/parser/lib/index.js:5135:28

  - index.js:6419 Object.parseParenAndDistinguishExpression
    [Website]/[@babel]/parser/lib/index.js:6419:14

  - index.js:2670 Object.parseParenAndDistinguishExpression
    [Website]/[@babel]/parser/lib/index.js:2670:18

  - index.js:6215 Object.parseExprAtom
    [Website]/[@babel]/parser/lib/index.js:6215:21

  - index.js:3552 Object.parseExprAtom
    [Website]/[@babel]/parser/lib/index.js:3552:20

  - index.js:5862 Object.parseExprSubscripts
    [Website]/[@babel]/parser/lib/index.js:5862:23

  - index.js:5842 Object.parseMaybeUnary
    [Website]/[@babel]/parser/lib/index.js:5842:21

  - index.js:5802 Object.parseExprOpBaseRightExpr
    [Website]/[@babel]/parser/lib/index.js:5802:34

  - index.js:5795 Object.parseExprOpRightExpr
    [Website]/[@babel]/parser/lib/index.js:5795:21

  - index.js:5774 Object.parseExprOp
    [Website]/[@babel]/parser/lib/index.js:5774:27

  - index.js:5739 Object.parseExprOps
    [Website]/[@babel]/parser/lib/index.js:5739:17

  - index.js:5702 Object.parseMaybeConditional
    [Website]/[@babel]/parser/lib/index.js:5702:23

  - index.js:5647 Object.parseMaybeAssign
    [Website]/[@babel]/parser/lib/index.js:5647:21

  - index.js:2621 Object.parseMaybeAssign
    [Website]/[@babel]/parser/lib/index.js:2621:18

Do you have any advice on how to debug this further? Same error with both the latest gatsby version and 2.1.37

**Comment by kkor** [comment]
The exact version that breaks it seems to be 3.0.0-alpha.19 -> 3.0.0-alpha.20.

**Comment by birkir** [comment]
What NodeJS version are you using? I can't seem to reproduce it locally, is there any chance to see from what file the error is coming.

Thanks @kkor

**Comment by kkor** [comment]
Uh I seem to be lagging behind quite a bit, I have node/v8.12.0 now, can try updating.
That was all that was in the logs ^ I can try debugging it further, I assume this should show me some info?: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/debugging-the-build-process.md

**Comment by birkir** [comment]
Fixed with latest version! 👍

**Comment by kkor** [comment]
Awesome, can confirm that it works now, thanks a bunch! 💯 
And sorry for not having the time to immediately debug it further!
