### ISSUE TITLE
TypeError: createContentDigest is not a function

### ISSUE THREAD

**Issue by kkor** [birkir/gatsby-source-prismic-graphql#26]
Moi,

So I've had preview: false until now, when I tried to enable it now I get this error with `gatsby develop` at the refetchInterval:

success extract queries from components — 0.189 s
error UNHANDLED EXCEPTION

  TypeError: createContentDigest is not a function

  - gatsby-node.js:146 createSchemaNode
    [Website]/[gatsby-source-graphql]/gatsby-node.js:146:29

  - gatsby-node.js:121 Timeout.refetcher [as _onTimeout]

The first build works fine, it's only whatever refetchInterval triggers that doesn't.

I can try to find the time later to dig deeper into the error and/or create a reproduction, but any pointers where to look are welcome. I've tried with both gatsby v2.1.37 and the newest.

**Comment by birkir** [comment]
Ok looks like it's erroring at gatsby-source-graphql.

I haven't tried this option yet. Maybe it's broken by default in gatsby-source-graphql

**Comment by kkor** [comment]
Oh you're right, I misread that the default was "60" instead of null... turning it off "resolves" this issue for me :)

**Comment by birkir** [comment]
You can track the upstream issue here: https://github.com/gatsbyjs/gatsby/issues/13239
