### ISSUE TITLE
Avoid loading prismic.min.js when not in preview

### ISSUE THREAD

**Issue by ffdead** [birkir/gatsby-source-prismic-graphql#27]
Would be great to avoid this extra request in production, but also keep the option to preview in production. Can we include it on demand when there is a preview cookie?

**Comment by arnaudlewis** [comment]
The script is not useful only for previews so I don't think it's a good
idea.
In addition to that, it makes sense to have previews in prod otherwise you
get rid of the benefit of releases and regular previews.

Le lun. 15 avr. 2019 à 21:31, David Lindkvist <notifications@github.com> a
écrit :

**Comment by ffdead** [comment]
Hi @arnaudlewis, can you please elaborate what other reasons are there to load this script?

I would only include it if there is a preview cookie (an approach we've successfully used on prismic powered websites in the past).

The Prismic toolbar which loads from this script, also loads `jquery-2.1.1.min.js` and a handful of request as a result, which affects the pagespeed score:

https://static.cdn.prismic.io/prismic.min.js
 https://antlerco.prismic.io/toolbar/bootstrap
https://antlerco.prismic.io/...ce930d7/previews-router
https://antlerco.prismic.io/...ce930d7/javascripts/bootstrap.js
https://antlerco.prismic.io/app/authenticated/v2
https://code.jquery.com/jquery-2.1.1.min.js

**Chrome DevTools audit:**

*Eliminate render-blocking resources*

URL | Size (KB) | Potential Savings (ms)
-- | -- | --
/prismic.min.js(static.cdn.prismic.io) | 61 KB | 1,220 ms

**Comment by arnaudlewis** [comment]
It's also useful for shared preview, the edit button, which is gonna be
updated soon to easily access your content from the website, and some other
features to come accessible via this toolbar.
If it's a matter of pagespeed, then we definitely need to work on this

Le mar. 16 avr. 2019 à 07:35, David Lindkvist <notifications@github.com> a
écrit :

**Comment by birkir** [comment]
I agree with arnaud, the benefits of having the prismic script could be beyond previews. It's a two way street for editing content.

I added a special flag (undocumented) if you really want to omit the script block.

https://github.com/birkir/gatsby-source-prismic-graphql/commit/e70c08fcab814aeaad0e2f72eb5b0c04da251d49

**Comment by ffdead** [comment]
Would you consider not loading this script in the head at least?

Currently, this script is the biggest reason for a low page speed index for us: https://www.dropbox.com/s/ne0p4oivw1kcc55/Screenshot%202019-05-02%2011.58.18.png?dl=0

Would be great if it could be async or loaded towards the bottom of the page.

**Comment by mvogel-dev** [comment]
It looks like the flag you added acts differently than it seemed at first glance. Nice work! The preview feature still works, and now it's getting 100/100 on Pagespeed Insights.

**Comment by birkir** [comment]
Great, glad to be at help 👍

**Comment by vasilenka** [comment]
@birkir @Decimator How do I actually use the flag? I just passed `omitScript: true` to the plugin options, but it's still blocking.

And can we have the script loads as an optional please? Yes it is useful, but only for when people use it.
It's pretty costly and affect the performance, and I just realize about it until I try to check the network request because my website loads so slow when it's just showing bunch of text served from prismic.

**Comment by birkir** [comment]
it's `omitPrismicScript: true`

**Comment by madeleineostoja** [comment]
Just wanted to chime in and say even without the `omitPrismicScript` flag, is there a reason the script is included in a render-blocking fashion in the head? Can it not be loaded async or deferred? That would alleviate the major perf issue without killing other functionality entirely

**Comment by mindmergedesign** [comment]
> It looks like the flag you added acts differently than it seemed at first glance. Nice work! The preview feature still works, and now it's getting 100/100 on Pagespeed Insights.

@Decimator how did you get the preview to work with the flag? If I add the `omitPrismicScript: true` flag, the preview stops working.
