### ISSUE TITLE
TypeError: Cannot read property 'prismic' of undefined

### ISSUE THREAD

**Issue by jodiedoubleday** [birkir/gatsby-source-prismic-graphql#30]
Everything seems to be working fine locally, I'm getting pages generate perfectly and previews working well, but I keep getting the same error which stops me deploying to netlify.

<img width="509" alt="Screen Shot 2019-04-24 at 10 34 52" src="https://user-images.githubusercontent.com/778942/56649237-a57e3380-667c-11e9-8732-680e569f66d9.png">

My repo can be found here - https://github.com/jodiedoubleday/HX-Gatsby/tree/previews

I contacted prismic who told me it was a problem with my setup but couldn't explain what. Was wondering if this is a known issue or if someone can spot a glaring error.

**Comment by birkir** [comment]
Yeah sure.

You have a typo in your TypeName from prismic.

Should be like this:

```js
    {
      resolve: `gatsby-source-prismic-graphql`,
      options: {
        repositoryName: `testeeee`, // (required)
        path: '/preview',       // (optional, default: /preview)
        previews: true,         // (optional, default: false)
        pages: [{               // (optional)
          type: 'Landing_page', // TypeName from prismic
          match: '/:uid',       // Pages will be generated under this pattern
          path: '/',            // Placeholder page for unpublished documents
          component: require.resolve('./src/templates/Landing.jsx'),
        }],
      }
    },
```

I'll improve error messages

**Comment by birkir** [comment]
3.1.3 now has better error messages in this scenario

**Comment by jodiedoubleday** [comment]
Ahh the old capital letter :) thank you so much!
