### ISSUE TITLE
Is it possible to change match: '/:uid' to something else?

### ISSUE THREAD

**Issue by jodiedoubleday** [birkir/gatsby-source-prismic-graphql#31]
More of a question than an issue (sorry if ive raised this in the wrong way)

Is there a way of changing
`match: '/:uid'`
to something like
`match: '/:slug` (or any other returned node from prismic?)

**Comment by birkir** [comment]
Currently, no, what is your use case?

`:uid` is just a parameter to match your Document's UID field in Prismic.

**Comment by jodiedoubleday** [comment]
use case is maybe very specific for our needs, but currently we use a `slug` in prismic so that our content team can give pages full paths i.e `gatsby/awesome.html`

You can't currently do this is UID (as slashes aren't allowed), but when I go to view previews, it uses UID's so it doesn't take you to preview the correct page, instead 404's.

I'm sure there is a different way around this in my particular repo, just wanted to check if there were other options.

**Comment by birkir** [comment]
So you have a document in Prismic you want to be accessible from `/foo/bar.html` on your website?

This is currently not supported with prismic's UIDs, so you would have to handle that yourself by doing a graphql query to fetch a custom field with the correct paths.

This plugin could however possibly have a feature with mapping function like so:

```js
match: '/pages/:uid',
mapParam(name, value) {
  if (name === 'uid') {
    return value.replace('__', '/');
  }
  return value;
}
```

So any page with UID as `foo__bar` would generate a page `pages/foo/bar`.

What do you think?

**Comment by jodiedoubleday** [comment]
sounds like a great solution, thanks

**Comment by davidkelley** [comment]
Hi, @birkir I hope you can help with this. I tried your suggestion as above, but it seems that the `mapParam` function is never called. Here is my configuration:

```
{
  resolve: 'gatsby-source-prismic-graphql',
  options: {
    linkResolver,
    accessToken: process.env.GATSBY_PRISMIC_KEY,
    repositoryName: process.env.GATSBY_PRISMIC_SITE,
    defaultLang: 'en-us',
    langs: ['en-us', 'fr-fr'],
    path: '/preview',
    previews: true,
    pages: [
      {
        type: 'Page',
        match: '/:uid',
        path: '/',
        component: require.resolve('./src/components/Page/index.jsx'),
        mapParam(name, value) {
          if (name === 'uid') {
            return value.replace('__', '/');
          }
          return value;
        }
      },
    ],
  }
}
```

I have a page with `uid` set to `faq__general` but the route remains `/faq__general` instead of `/faq/general`.

**Comment by kb1995** [comment]
Any updates to this? A feature like this would be amazing
