### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by trickydisco78** [birkir/gatsby-source-prismic-graphql#37]
I have an issue using the prismic plugin. Everything works fine in develop mode. Data is coming back and preview seems to work fine. However if i build it looks like the data isn;'t available at build time?

`error Building static HTML failed for path "/events"`

`See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html`

   `8 |   return (`
   `9 |     <>`
`> 10 |       <SEO title={Event: ${data.event_title[0].text}} />`
     |                                  ^
` 11 |       <h1>{data.event_title[0].text}</h1>`
 ` 12 |       <p>{`Event date: ${data.event_date}`}</p>`
 '`13 |       <p>{`Location: ${data.location[0].text}`}</p>`

  `WebpackError: TypeError: Cannot read property 'event_title' of null'`

Component looks like this
`const Event = ({ data: { prismic } }) => {`
  `const data = prismic.event`
  `return (`
    `<>`
     ` <SEO title={`Event: ${data.event_title[0].text}`} />`
     `h1>{data.event_title[0].text}</h1>`
      `<p>{`Event date: ${data.event_date}`}</p>`
      `<p>{`Location: ${data.location[0].text}`}</p>`
      `<Link to="/events">Back to Events</Link>`
    `</>`
  `)`
`}`

`Event.query = query'`

using
`"gatsby": "2.3.16",
"gatsby-source-prismic-graphql": "^3.1.3",`

I'm console logging the data in the component and it looks fine in the build process but fails when it gets the component bit     ` <SEO title={`Event: ${data.event_title[0].text}`} />`. This is happening for lots of components

**Comment by trickydisco78** [comment]
Have been debugging this for a day or 2 but can't work out why data isn't available at build time. I even console log out the data prop which shows in the build process 
![Screenshot 2019-05-16 at 15 42 56](https://user-images.githubusercontent.com/3627429/57863074-5184eb80-77f1-11e9-890f-4ab2f74e8b9a.png)
and everything is as should be??

**Comment by birkir** [comment]
Maybe the data isn't published yet, but the draft is.

So you have to use lodash/get to ensure its not crashing.

```jsx
import { get } from 'lodash';
// ...
<h1>{get(data.prismic, 'job_listing.job_title.0.text', 'not found')}</h1>
```

**Comment by trickydisco78** [comment]
Cheers. Seems there's something going on with thr lifecycle of the data at build time. it appears at build time the local variable 'data'  isn't available. If i use the get utility from lodash and pass in the data.prismic object it works?! Wondering what happens with gatsby at build time and what data it has access to and how this differs at runtime in dev mode. I'm guessing dev mode is basically running a mounted app

**Comment by GreatState** [comment]
Does the graphql plugin effectively hit the draft state of documents in prismic? or is a payload included with the request and somehow uses the graphql query in the component?

**Comment by trickydisco78** [comment]
It seems weird that i have to rely on the get lodash package when the data should be available on the data.prismic object. Not sure why it's not available at build time?

**Comment by trickydisco78** [comment]
Do we know why the object isn't available at build time?

I just added a console log to your pagination example: https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/examples/pagination/src/templates/article.js

instead of using get i'm trying to access the object directly

``` console.log(props.data.prismic.allArticles.edges[0].node.title);```

and i'm getting the same kind of error

WebpackError: TypeError: Cannot read property 'node' of undefined

**Comment by whmountains** [comment]
This reminds me of gatsbyjs/gatsby#8790

**Comment by birkir** [comment]
> Do we know why the object isn't available at build time?
> 
> I just added a console log to your pagination example: https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/examples/pagination/src/templates/article.js
> 
> instead of using get i'm trying to access the object directly
> 
> ` console.log(props.data.prismic.allArticles.edges[0].node.title);`
> 
> and i'm getting the same kind of error
> 
> WebpackError: TypeError: Cannot read property 'node' of undefined

Because drafts will not be available on build time, only runtime. This is the nature of Gatsby and the whole purpose of the plugin.

You can either use [lodash.get](https://lodash.com/docs/4.17.11#get), [@babel/plugin-proposal-optional-chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining) or [ts-optchain](https://github.com/rimeto/ts-optchain) if you use typescript.

```js
// lodash get
const title = get(data, 'prismic.allArticles.edges.0.node.title', 'no title yet');

// babel optional chaining
const title = data?.prismic?.allArticles?.edges?[0].?node.?title || 'no title yet';

// ts-optchain
const title = oc(data).prismic.allArticles.edges[0].node.title('no title yet');
```

I'm closing this issue for now.
