### ISSUE TITLE
Comments in GraphQL queries break Previews

### ISSUE THREAD

**Issue by kkor** [birkir/gatsby-source-prismic-graphql#38]
With a simple template query:

```
export const query = graphql`
    query PageByUid($uid: String!) {
        prismic {
            page(uid: $uid, lang: "en-us") {
                title
                #ingress <--- without the comment this works
            }
        }
    }
`;
```
the preview functionality breaks if # comments are inserted with the following error in the browser:

GraphQLError
locations: [{…}]
message: "Syntax Error: Expected Name, found <EOF>"
extensions: undefined
nodes: undefined
originalError: undefined
path: undefined
positions: [98]
source: Source
body: " query PageByUid($uid: String!) { prismic { page(uid: $uid, lang: "en-us") { title #ingress } } } "
locationOffset: {line: 1, column: 1}
name: "GraphQL request"
Symbol(Symbol.toStringTag): (...)
__proto__: Object
stack: "GraphQLError: Syntax Error: Expected Name, found <EOF>↵    at syntaxError (http://localhost:8008/commons.js:24626:10)↵    at expectToken (http://localhost:8008/commons.js:29636:67)↵    at parseName (http://localhost:8008/commons.js:28303:15)↵    at parseField (http://localhost:8008/commons.js:28518:21)↵    at parseSelection (http://localhost:8008/commons.js:28507:104)↵    at many (http://localhost:8008/commons.js:29727:16)↵    at parseSelectionSet (http://localhost:8008/commons.js:28494:17)↵    at parseField (http://localhost:8008/commons.js:28535:91)↵    at parseSelection (http://localhost:8008/commons.js:28507:104)↵    at many (http://localhost:8008/commons.js:29724:16)↵    at parseSelectionSet (http://localhost:8008/commons.js:28494:17)↵    at parseField (http://localhost:8008/commons.js:28535:91)↵    at parseSelection (http://localhost:8008/commons.js:28507:104)↵    at many (http://localhost:8008/commons.js:29724:16)↵    at parseSelectionSet (http://localhost:8008/commons.js:28494:17)↵    at parseOperationDefinition (http://localhost:8008/commons.js:28422:19)↵    at parseExecutableDefinition (http://localhost:8008/commons.js:28375:16)↵    at parseDefinition (http://localhost:8008/commons.js:28339:16)↵    at many (http://localhost:8008/commons.js:29724:16)↵    at parseDocument (http://localhost:8008/commons.js:28320:18)↵    at parse (http://localhost:8008/commons.js:28258:10)↵    at parseDocument (http://localhost:8008/commons.js:24112:16)↵    at gql (http://localhost:8008/commons.js:24153:10)↵    at getQuery (http://localhost:8008/commons.js:21476:36)↵    at getIsolatedQuery (http://localhost:8008/commons.js:21485:15)↵    at http://localhost:8008/commons.js:22327:69"
__proto__: Error

**Comment by birkir** [comment]
Nice catch. I'll remove comments before trimming whitespace!

**Comment by birkir** [comment]
This has been fixed with latest version

**Comment by nickmcmillan** [comment]
FWIW I'm experiencing a similar (if not same) issue. Previews works, then I'll add a GraphQL comment, restart the gatsby dev server and hit the preview button again, and an error is logged to the console;

`message: "Syntax Error: Expected Name, found <EOF>"`

I'm using `"gatsby-source-prismic-graphql": "^3.4.0-beta.2"`.
