### ISSUE TITLE
Changes in Prismic data structures don't populate?

### ISSUE THREAD

**Issue by philschanely** [birkir/gatsby-source-prismic-graphql#40]
Hello! Thank you for this great plugin. I am relatively new to GraphQL, Gatsby and Prismic, but excited about what I'm learning.

One issue I've encountered is that when I am developing in Gatsby using this plugin and I change my types or data structure in Prismic, I am not able to immediately use the new properties or types in Gatsby. It seems the GraphQL schema does not sync? Or perhaps its on the Prismic side?

I appreciate any clarification you can provide!

Best,
Phil

**Comment by philschanely** [comment]
I think I figured it out... seems that the new structures and data types appear after two other conditions are met:

- I must have at least one item that has content populated in the new type or data structure from Prismic.
- I must restart the app locally.

I'll close this issue. Sorry for the trouble!

**Comment by birkir** [comment]
I think just any document can be saved in prismic to refresh the graphql schema. (Maybe it needs to be published, not really sure)

Semi bug on prismic side

**Comment by marguerrrite** [comment]
I am also having this issue. Even though I see the data refreshed in Prismic's API browser, no amount of updating content or clearing the cache refreshes data and structures when using GraphiQL.

My non-glamorous workaround is to stop the server, change the Prismic repository name in `gatsby-config.js` to something incorrect, restart the server, let it error, then stop it again and change the repo name back to the correct one.

Then when I restart, I see the updated structure in GraphiQL's Explorer.

**Comment by matthewlein** [comment]
I had to delete the `.cache` folder to get fresh schema for anyone else looking for a solution.

**Comment by danniing** [comment]
> I had to delete the `.cache` folder to get fresh schema for anyone else looking for a solution.

You can also run `gatsby clean` which deletes the **.cache** and **public** directories
