### ISSUE TITLE
bump gatsby-source-graphql

### ISSUE THREAD

**Issue by eknowles** [birkir/gatsby-source-prismic-graphql#54]
Gatsby build and develop pushes this warning on each page

```
Calling "createPageDependency" directly from actions in deprecated. Use "createPageDependency" from "gatsby/dist/redux/actions/add-page-dependency".
```

This warning is due to `gatsby-source-graphql`. Please upgrade to min 2.0.19 https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-graphql/CHANGELOG.md#2019-2019-06-10

**Comment by birkir** [comment]
3.4.0-beta.1 now has updated deps.

You can also force install gatsby-source-graphql-universal@3.1.6

Let me know if this helps!
