### ISSUE TITLE
Support for Prismic slices / Linked documents?

### ISSUE THREAD

**Issue by kkor** [birkir/gatsby-source-prismic-graphql#6]
The query for getting slice content requires an inline fragment:
https://prismic.io/docs/graphql/query-the-api/retrieve-slice-content

which will throw:
index.js:2177 You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. To make this error go away, use the `IntrospectionFragmentMatcher` as described in the docs: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher
WARNING: heuristic fragment matching going on!

I didn't test this (because all my links are inside slices :) ), but the linked documents also require inline fragments:
https://prismic.io/docs/graphql/query-the-api/retrieve-link-content

So I assume they would throw the same error?

**Comment by birkir** [comment]
We should be able to support this by implementing the proposed code to fetch the fragment types with GraphQL.

Hopefully this could be done synchronously before the IntrospectionFragmentMatcher is bootstrapped.

**Comment by kkor** [comment]
That's good news, because 98% of my content will be inside of slices :)
So for now I'll stop creating more issues, because this is as far as I can get with my setup!
Thanks again for the great support!

**Comment by ffdead** [comment]
Hi guys. I agree it would be awesome to get support for Slices since we also use that a lot. 

Wish I knew how to help, I'm still learning how Gatsby works :)

**Comment by birkir** [comment]
Fragments are now supported on the client side ;)

**Comment by ffdead** [comment]
@birkir Brilliant! 

Btw, did you forget to push v2.3 to this repo?
