### ISSUE TITLE
[Question] Custom match variable

### ISSUE THREAD

**Issue by Exegetech** [birkir/gatsby-source-prismic-graphql#64]
Sorry if this is in the docs. I tried to look for it but couldn't find it.

I have a custom type, that is `Article`, but want to publish the route under different `Author`s.

```
{
  pages: [{
    type: 'Article',
    match: '/article/:author/:uid',
    path: '/article',
    component: require.resolve('./src/templates/article.js'),
  }],
}
```

Example generated urls

```
/article/christian/foo-bar
/article/christian/hello-world
/article/sakai/leet
/article/sakai/uber-hacker
```

Is this possible?

**Comment by birkir** [comment]
Currently only uid is available in the URL.

You can solve this by doing something similar in gatsby-node.js:
```js
exports.createPages = ({ graphql, actions }) => {
  const { data, errors } = await graphql(`
    query {
      allArticle {
        edges {
          node {
            _meta { uid }
            author { _meta { uid } }
          }
        }
      }
    }
  `);

  data.allArticle.edges.map(({ node }) => actions.createPage({
    path: `/article/${node.author._meta.uid}/${node._meta.uid}`
    component: require.resolve('./src/templates/article.js'),
    context: {
      ...node,
    },
  }));
};
```

**Comment by Exegetech** [comment]
Thank you @birkir this works!

**Comment by erikjalevik** [comment]
This means that I would have to exclude this type from `options.pages` in the plugin configuration in gatsby-config.js, right? Meaning I'd lose all the other functionality (like previews) that the plugin provides?

If I don't, it generates every page twice.

**Comment by birkir** [comment]
Previews will work, auto generated pages also will work, but you should exclude them, yes.

**Comment by erikjalevik** [comment]
Thanks for the quick reply, I will try it out.

However, how can I deal with this scenario in the link resolver? It is only passed the document's UID (along with a few other predefined values), but here I would need some more data (the author in the OP's example) to be able to resolve the full URL.
