### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by RobinHerzog** [birkir/gatsby-source-prismic-graphql#65]
Hello,

My prismic has 200 pages. I need to create them all on gatsby-node. How do you run the pagination on that page?

**Comment by birkir** [comment]
https://github.com/birkir/gatsby-source-prismic-graphql/tree/master/examples/pagination

**Comment by RobinHerzog** [comment]
I'm generating 200 pages that has no relationship. I have to create my pages on gatsby-node. Your links does not resolve my issue.
