### ISSUE TITLE
i.StaticQuery.propTypes is undefined

### ISSUE THREAD

**Issue by Exegetech** [birkir/gatsby-source-prismic-graphql#69]
When trying to build Gatsby using `gatsby-source-prismic-graphql`, I got the following error

![Screen Shot 2019-08-08 at 11 01 24 PM](https://user-images.githubusercontent.com/7025139/62751089-7d022580-ba30-11e9-82dd-e5e219279962.png)

Here is the repo that produced the issue

https://github.com/christiansakai/gatsby-site-broken

**Comment by raroul** [comment]
Hello @christiansakai, I think your problem is related to this pull request https://github.com/birkir/gatsby-source-prismic-graphql/pull/57
Just update to **3.4.0-beta.1** it should solve this issue

**Comment by Exegetech** [comment]
@raroul Thank you! Appreciate the quick response
