### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kkor** [birkir/gatsby-source-prismic-graphql#7]
Long time no see 👋 

I'm using this plugin with the preview disabled, and was trying out the pagination. [In your example](https://github.com/birkir/gatsby-source-prismic-graphql#pagination-and-other-dynamic-fetching) `prismic.load()` gets passed as prop to the React Component, but the only prop that gets passed down for me is the graphql data in `data.prismic`. 

I tried enabling the preview and even checking the props in the preview/ version, but it's not there... do I need to do some other undocumented magic to get access to the load function and does it work with the preview disabled?

Thanks again!

**Comment by birkir** [comment]
This is correct, the plugin doesn't wrap your pages with that functionality (yet)

I see no reason why we can't add it ! 👍

**Comment by kkor** [comment]
Okay! Until then, is there a workaround to fetch the next documents with the load function or through some other way?

**Comment by birkir** [comment]
Published in 2.3.1
