### ISSUE TITLE
Support for the new schema customization API?

### ISSUE THREAD

**Issue by madeleineostoja** [birkir/gatsby-source-prismic-graphql#71]
Coming from `gatsby-source-prismic`, one of the very useful features it now includes in v3 is out-of-the-box support for [providing Prismic's JSON schemas to Gatsby](https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/README.md#providing-json-schemas) using the new schema customization API, to get around Gatsby throwing on fields without data. 

Are there any plans to support something similar in this plugin? The rest of the sugar provided by the higher-level API is great, and using the new GraphQL API is awesome. But missing schemas are my biggest pain point atm.

**Comment by birkir** [comment]
I don't understand the problem. The JSON Schema is a solution to a problem we don't have with this plugin.

Are you saying the GraphQL schema is missing fields and stuff?

**Comment by madeleineostoja** [comment]
Oh! Maybe I've misunderstood what the GraphQL API allows and this is a non-issue. 

If you try to fetch a field that doesn't have any content saved on Prismic, would Gatsby still not throw? I thought that was the nature of GraphQL, you can only query fields that exist with data. Or does the new API make everything defined in your content models available, regardless of whether there's content saved?

**Comment by birkir** [comment]
> If you try to fetch a field that doesn't have any content saved on Prismic, would Gatsby still not throw? I thought that was the nature of GraphQL, you can only query fields that exist with data.

The GraphQL schema will reflect the Prismic schema and has nothing to do with the data.

> Or does the new API make everything defined in your content models available, regardless of whether there's content saved?

Yes. However, there is a bug in Prismic where the schema won't update unless you save a document (any document will do, it will clear the complete schema cache).

I hope this answers your question 😃

**Comment by madeleineostoja** [comment]
Amazing, and sorry for the false alarm 😅
