### ISSUE TITLE
Preview does not redirect to correct page

### ISSUE THREAD

**Issue by benhodgson87** [birkir/gatsby-source-prismic-graphql#79]
Have an issue that previews _sort of_ work, but the preview endpoint does not seem to redirect users to the correct page, it just hangs on a blank page (with the Prismic toolbar).

If you then navigate to the expected url manually it correctly loads the preview, so the cookie seems to be setting as expected, but the preview endpoint does not redirect after doing so.

If the preview is set up in Prismic to resolve to `/preview`, the url the button takes you to is just `/preview`, but if I change the resolve path to `/preview/` with a trailing slash, it includes the token after `/preview`. However neither takes the user to the correct page after setting the cookie.

`/preview`:
<img width="1402" alt="Screenshot 2019-09-20 at 16 12 04" src="https://user-images.githubusercontent.com/189707/65338203-99fa4e80-dbc1-11e9-8fb5-60f5dd6a524a.png">

`/preview/`:
<img width="1400" alt="Screenshot 2019-09-20 at 16 16 24" src="https://user-images.githubusercontent.com/189707/65338421-12f9a600-dbc2-11e9-96a9-a2873c9b0355.png">

Config:
```js
{
      resolve: `gatsby-source-prismic-graphql`,
      options: {
        repositoryName: 'xxx-xxx',
        path: '/preview',
        previews: true,
        omitPrismicScript: false,
        pages: [
          {
            type: 'Landingpage',
            match: '/:uid',
            path: '/',
            component: require.resolve('./src/templates/landing.js'),
          },
        ],
      },
    },
```

NPM Version:
```json
"gatsby-source-prismic-graphql": "^3.4.0-beta.2",
```

Any help appreciated.

**Comment by birkir** [comment]
Did you add the link resolver to your `gatsby-browser.js`?

Bottom here: https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/packages/gatsby-source-prismic-graphql/README.md#getting-started

**Comment by benhodgson87** [comment]
It was in there, but seems like there was a difference in implementation; the linkResolver I had was using an ES6 default export rather than module.exports. Can only assume this was the cause. Switching it to match the example has it working now. Thanks for your help 👍

**Comment by ecomonestop** [comment]
I experience the same issue described here even after using module.exports.  The thing is preview works fine on my local machine, but in AWS S3, I experience the symptoms described here whether using module.exports or ES6 syntax.  Is there any special setting I need to set on AWS S3 to make it work with Preview?

**Comment by ecomonestop** [comment]
I resolved my issue by setting /preview/index.html   instead of just /preview
