### ISSUE TITLE
Rich text

### ISSUE THREAD

**Issue by mverissimo** [birkir/gatsby-source-prismic-graphql#81]
Hi, I', trying render a rich-text but, I see that expect the following props:
`
[{
      type: '',
      text: '',
      spans: []
}]
`

but the graphql data return something like that:
`
data {
  description {
    raw {
      type
      text
     }
     html
     text
    }
}
`
However this not render the component I'm using prismic-reactjs

**Comment by arnaudlewis** [comment]
Hi @mverissimo,
Are you sure that you raised your issue on the right plugin? Maybe you use `gatsby-source-prismic` which relies on Prismic's Rest API and not the GraphQL one.
What you describe seems to correspond to this: https://github.com/angeloashmore/gatsby-source-prismic/blob/80f2fc1e4bf514fb23b125a678bc1d984d1e2ffb/src/normalize.js#L45

**Comment by mverissimo** [comment]
@arnaudlewis You're right, thanks for the help, and sorry about my lack of attention.
