### ISSUE TITLE
multilang: preview does not work if lang param is used in query

### ISSUE THREAD

**Issue by ascii-husky** [birkir/gatsby-source-prismic-graphql#86]
Hey

Thanks for this plugin!

If I use a lang param in a page query like this : `allPosts(uid: $uid, lang: $lang) {...` 
The `lang` from the query wont be set because of this check `if (!params[key] && qs.has(key))`
here: https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/packages/gatsby-source-prismic-graphql/src/components/WrapPage.tsx#L66

It does not matter if the languages share the same `uid` or not.

If I remove `!params[key]`, previews work for each language in my use case. 
But I didn't test this with other configurations.

Is the above check necessary?

Thanks

**Comment by Duaner** [comment]
Hello @ascii-husky ,

This should work, by default with the latest version of the plugin. What is the error that you're having? 

Did you register your link resolver in your gatsby browser? 

```
const { registerLinkResolver } = require("gatsby-source-prismic-graphql")
const { linkResolver } = require("./src/utils/linkResolver")
registerLinkResolver(linkResolver)

```

**Comment by ascii-husky** [comment]
Hey

No it still does not work with version 3.4.0-beta.2.
I simply get a blank site for the preview.

The link resolver is registered exactly like this:

```
const { registerLinkResolver } = require('gatsby-source-prismic-graphql');
const { linkResolver } = require('./src/utils/linkResolver');

registerLinkResolver(linkResolver);
```

Atm I am using a fork with the removed `!params[key]` check, from here https://github.com/KiloKilo/gatsby-source-prismic-graphql/blob/multilang-preview/packages/gatsby-source-prismic-graphql/src/components/WrapPage.tsx#L66

This is working fine.

Thanks

**Comment by Duaner** [comment]
I don't have the problem my self with the regular plugin. Can you give me access to your repository?

**Comment by MadsMadsDk** [comment]
I'm still experiencing problems with this. Actually I have problems getting any previews working at all, not just drafts. What am I doing wrong?

I've tried to create a super simple repository, which you can find here: https://github.com/MadsMadsDk/prismic-preview-i18n-gatsby-test
