### ISSUE TITLE
ImageSharp doesn't work in gatsby-node.js

### ISSUE THREAD

**Issue by dromedar-design** [birkir/gatsby-source-prismic-graphql#98]
I'm not sure if this is intended / expected behaviour, but I can't make images work properly with createPages in gatsby-node.js. Any way around this?

```
"gatsby-node.js" threw an error while running the createPages lifecycle:

Unknown fragment "GatsbyImageSharpFluid_withWebp".

GraphQL request:20:44
19 |                                     fluid(maxWidth: 1920) {
20 |                                         ...GatsbyImageSharpFluid_withWebp
   |                                            ^
21 |                                     }
```

**Comment by kamerondotcom** [comment]
Is there a reason you want to make those queries in gatsy-node? Typically you'd make those queries on the page or component level, typically gatsby-node is reserved for fetching out more structural data to build out your page hierarchy.

https://prismic.io/docs/reactjs/getting-started/prismic-gatsby
^^ Has some good concepts re: page creation.

**Comment by dromedar-design** [comment]
For my use case I want to query all items at once (more than 20), so my solution was to recursively get all documents in gatsby-node.js to bypass the pagination limit. It's working out great except for the images. Is this a bad practice?

**Comment by LekoArts** [comment]
Those fragments don't work in gatsby-node.js, you have to write out all properties yourself or define the fragment yourself at the top. This is not an issue with the source plugin.

**Comment by dromedar-design** [comment]
Yeah, you're right. For future reference you can find those [in this file](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/fragments.js).

So instead of writing this:
```
imageSharp {
    childImageSharp {
        fluid(maxWidth: 1920) {
            ...GatsbyImageSharpFluid_withWebp
        }
    }
}
```
you can write this:
```
imageSharp {
    childImageSharp {
        fluid(maxWidth: 1920) {
            base64
            aspectRatio
            src
            srcSet
            srcWebp
            srcSetWebp
            sizes
        }
    }
}
```
and it will work the same.
