### ISSUE TITLE
GraphQL doesn't see Prismic Custom Types

### ISSUE THREAD

**Issue by jonybekov** [birkir/gatsby-source-prismic-graphql#99]
I have a bunch of content types that I am able to use. However the content types I added recently are invisible in GraphiQL. I've relaunched my gatsby server couple times but it's not seems to work.

Here's my custom types list

![image](https://user-images.githubusercontent.com/39439363/69006057-c9240680-094b-11ea-805c-a434659f925a.png)
All custom types are working except 'about' and 'partner'

![image](https://user-images.githubusercontent.com/39439363/69006074-04bed080-094c-11ea-80ec-912e54e9aec4.png)

Here's my gatsby-config.js

`require('dotenv').config({
	path: `.env`
});

module.exports = {
	siteMetadata: {
		title: `Gatsby Default Starter`,
		description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
		author: `@gatsbyjs`
	},
	plugins: [
		`gatsby-plugin-react-helmet`,
		{
			resolve: `gatsby-source-filesystem`,
			options: {
				name: `images`,
				path: `${__dirname}/src/images`
			}
		},
		`gatsby-transformer-sharp`,
		`gatsby-plugin-sharp`,
		{
			resolve: `gatsby-plugin-manifest`,
			options: {
				name: `gatsby-starter-default`,
				short_name: `starter`,
				start_url: `/`,
				background_color: `#663399`,
				theme_color: `#663399`,
				display: `minimal-ui`,
				icon: `src/images/gatsby-icon.png` // This path is relative to the root of the site.
			}
		},
		{
			resolve: `gatsby-source-prismic-graphql`,
			options: {
				repositoryName: process.env.PRISMIC_REPOSITORY_NAME,
				accessToken: process.env.PRISMIC_ACCESS_TOKEN
			}
		}
	]
};
`

**Comment by alessiodionisi** [comment]
Try deleting the `.cache` folder

**Comment by zeekrey** [comment]
Had the same problem and deleting the `.cache` folder worked for me.

**Comment by Duaner** [comment]
Hey, @Teo0303 Did you published documents for those types. 

By running gatsby clean this should solve it. 

Do you still have this issue or can this issue be closed?

**Comment by jonybekov** [comment]
> Hey, @Teo0303 Did you published documents for those types.
> 
> By running gatsby clean this should solve it.
> 
> Do you still have this issue or can this issue be closed?

I solved this issue by re-runing command `gatsby develop`.
Thanks for all who helped to figure out this issue.
